apiVersion: v1
kind: Service
metadata:
  name: helm3-kubectl-node
spec:
  selector:
    app: helm3-kubectl-node
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: 8443
  type: LoadBalancer