apiVersion: apps/v1
kind: Deployment
metadata:
  name: stellar
  labels:
    app: stellar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stellar
  template:
    metadata:
      labels:
        app: stellar
    spec:
      containers:
      - name: kubernetes-stellar
        image: reneschoonrok/kubernetes-stellar:latest
        env:
        - name: TOKEN
          value: "exposed"